/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type TraceTransformer from '#app/traces/transformers/trace_transformer'
import type SpanTransformer from '#app/traces/transformers/span_transformer'
import type QueryTransformer from '#app/queries/transformers/query_transformer'
import type LogTransformer from '#app/logs/transformers/log_transformer'
import type JobTransformer from '#app/jobs/transformers/job_transformer'
import type ExternalCallTransformer from '#app/external_calls/transformers/external_call_transformer'
import type ExceptionTransformer from '#app/exceptions/transformers/exception_transformer'
import type CommandTransformer from '#app/commands/transformers/command_transformer'

export namespace Data {
  export type Trace = InferData<TraceTransformer>
  export namespace Trace {
    export type Variants = InferVariants<TraceTransformer>
  }
  export type Query = InferData<QueryTransformer>
  export namespace Query {
    export type Variants = InferVariants<QueryTransformer>
  }
  export type Exception = InferData<ExceptionTransformer>
  export namespace Exception {
    export type Variants = InferVariants<ExceptionTransformer>
  }
  export type Log = InferData<LogTransformer>
  export namespace Log {
    export type Variants = InferVariants<LogTransformer>
  }
  export type Span = InferData<SpanTransformer>
  export namespace Span {
    export type Variants = InferVariants<SpanTransformer>
  }
  export type Job = InferData<JobTransformer>
  export namespace Job {
    export type Variants = InferVariants<JobTransformer>
  }
  export type Command = InferData<CommandTransformer>
  export namespace Command {
    export type Variants = InferVariants<CommandTransformer>
  }
  export type ExternalCall = InferData<ExternalCallTransformer>
  export namespace ExternalCall {
    export type Variants = InferVariants<ExternalCallTransformer>
  }
}
