/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { DateTime } from 'luxon'
import { BaseModel, column } from '@adonisjs/lucid/orm'

export class NoteSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'title'] as const
  $columns = NoteSchema.$columns
  @column()
  declare body: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare title: string
}
