/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as LocaleAuthRouteRouteImport } from './routes/$locale/auth/route'
import { Route as LocaledashboardRouteRouteImport } from './routes/$locale/(dashboard)/route'
import { Route as LocaledashboardIndexRouteImport } from './routes/$locale/(dashboard)/index'
import { Route as LocaleAuthVerifyEmailIndexRouteImport } from './routes/$locale/auth/verify-email/index'
import { Route as LocaleAuthSignupIndexRouteImport } from './routes/$locale/auth/signup/index'
import { Route as LocaleAuthResetPasswordIndexRouteImport } from './routes/$locale/auth/reset-password/index'
import { Route as LocaleAuthResendVerificationIndexRouteImport } from './routes/$locale/auth/resend-verification/index'
import { Route as LocaleAuthLoginIndexRouteImport } from './routes/$locale/auth/login/index'
import { Route as LocaleAuthForgotPasswordIndexRouteImport } from './routes/$locale/auth/forgot-password/index'
import { Route as LocaledashboardAdminIndexRouteImport } from './routes/$locale/(dashboard)/admin/index'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAuthRouteRoute = LocaleAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaledashboardRouteRoute = LocaledashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaledashboardIndexRoute = LocaledashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaledashboardRouteRoute,
} as any)
const LocaleAuthVerifyEmailIndexRoute =
  LocaleAuthVerifyEmailIndexRouteImport.update({
    id: '/verify-email/',
    path: '/verify-email/',
    getParentRoute: () => LocaleAuthRouteRoute,
  } as any)
const LocaleAuthSignupIndexRoute = LocaleAuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => LocaleAuthRouteRoute,
} as any)
const LocaleAuthResetPasswordIndexRoute =
  LocaleAuthResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => LocaleAuthRouteRoute,
  } as any)
const LocaleAuthResendVerificationIndexRoute =
  LocaleAuthResendVerificationIndexRouteImport.update({
    id: '/resend-verification/',
    path: '/resend-verification/',
    getParentRoute: () => LocaleAuthRouteRoute,
  } as any)
const LocaleAuthLoginIndexRoute = LocaleAuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => LocaleAuthRouteRoute,
} as any)
const LocaleAuthForgotPasswordIndexRoute =
  LocaleAuthForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => LocaleAuthRouteRoute,
  } as any)
const LocaledashboardAdminIndexRoute =
  LocaledashboardAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => LocaledashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/': typeof LocaledashboardIndexRoute
  '/$locale/auth': typeof LocaleAuthRouteRouteWithChildren
  '/$locale/admin': typeof LocaledashboardAdminIndexRoute
  '/$locale/auth/forgot-password': typeof LocaleAuthForgotPasswordIndexRoute
  '/$locale/auth/login': typeof LocaleAuthLoginIndexRoute
  '/$locale/auth/resend-verification': typeof LocaleAuthResendVerificationIndexRoute
  '/$locale/auth/reset-password': typeof LocaleAuthResetPasswordIndexRoute
  '/$locale/auth/signup': typeof LocaleAuthSignupIndexRoute
  '/$locale/auth/verify-email': typeof LocaleAuthVerifyEmailIndexRoute
}
export interface FileRoutesByTo {
  '/$locale/auth': typeof LocaleAuthRouteRouteWithChildren
  '/$locale': typeof LocaledashboardIndexRoute
  '/$locale/admin': typeof LocaledashboardAdminIndexRoute
  '/$locale/auth/forgot-password': typeof LocaleAuthForgotPasswordIndexRoute
  '/$locale/auth/login': typeof LocaleAuthLoginIndexRoute
  '/$locale/auth/resend-verification': typeof LocaleAuthResendVerificationIndexRoute
  '/$locale/auth/reset-password': typeof LocaleAuthResetPasswordIndexRoute
  '/$locale/auth/signup': typeof LocaleAuthSignupIndexRoute
  '/$locale/auth/verify-email': typeof LocaleAuthVerifyEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/(dashboard)': typeof LocaledashboardRouteRouteWithChildren
  '/$locale/auth': typeof LocaleAuthRouteRouteWithChildren
  '/$locale/(dashboard)/': typeof LocaledashboardIndexRoute
  '/$locale/(dashboard)/admin/': typeof LocaledashboardAdminIndexRoute
  '/$locale/auth/forgot-password/': typeof LocaleAuthForgotPasswordIndexRoute
  '/$locale/auth/login/': typeof LocaleAuthLoginIndexRoute
  '/$locale/auth/resend-verification/': typeof LocaleAuthResendVerificationIndexRoute
  '/$locale/auth/reset-password/': typeof LocaleAuthResetPasswordIndexRoute
  '/$locale/auth/signup/': typeof LocaleAuthSignupIndexRoute
  '/$locale/auth/verify-email/': typeof LocaleAuthVerifyEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$locale'
    | '/$locale/'
    | '/$locale/auth'
    | '/$locale/admin'
    | '/$locale/auth/forgot-password'
    | '/$locale/auth/login'
    | '/$locale/auth/resend-verification'
    | '/$locale/auth/reset-password'
    | '/$locale/auth/signup'
    | '/$locale/auth/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$locale/auth'
    | '/$locale'
    | '/$locale/admin'
    | '/$locale/auth/forgot-password'
    | '/$locale/auth/login'
    | '/$locale/auth/resend-verification'
    | '/$locale/auth/reset-password'
    | '/$locale/auth/signup'
    | '/$locale/auth/verify-email'
  id:
    | '__root__'
    | '/$locale'
    | '/$locale/(dashboard)'
    | '/$locale/auth'
    | '/$locale/(dashboard)/'
    | '/$locale/(dashboard)/admin/'
    | '/$locale/auth/forgot-password/'
    | '/$locale/auth/login/'
    | '/$locale/auth/resend-verification/'
    | '/$locale/auth/reset-password/'
    | '/$locale/auth/signup/'
    | '/$locale/auth/verify-email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/auth': {
      id: '/$locale/auth'
      path: '/auth'
      fullPath: '/$locale/auth'
      preLoaderRoute: typeof LocaleAuthRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/(dashboard)': {
      id: '/$locale/(dashboard)'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaledashboardRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/(dashboard)/': {
      id: '/$locale/(dashboard)/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaledashboardIndexRouteImport
      parentRoute: typeof LocaledashboardRouteRoute
    }
    '/$locale/auth/verify-email/': {
      id: '/$locale/auth/verify-email/'
      path: '/verify-email'
      fullPath: '/$locale/auth/verify-email'
      preLoaderRoute: typeof LocaleAuthVerifyEmailIndexRouteImport
      parentRoute: typeof LocaleAuthRouteRoute
    }
    '/$locale/auth/signup/': {
      id: '/$locale/auth/signup/'
      path: '/signup'
      fullPath: '/$locale/auth/signup'
      preLoaderRoute: typeof LocaleAuthSignupIndexRouteImport
      parentRoute: typeof LocaleAuthRouteRoute
    }
    '/$locale/auth/reset-password/': {
      id: '/$locale/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/$locale/auth/reset-password'
      preLoaderRoute: typeof LocaleAuthResetPasswordIndexRouteImport
      parentRoute: typeof LocaleAuthRouteRoute
    }
    '/$locale/auth/resend-verification/': {
      id: '/$locale/auth/resend-verification/'
      path: '/resend-verification'
      fullPath: '/$locale/auth/resend-verification'
      preLoaderRoute: typeof LocaleAuthResendVerificationIndexRouteImport
      parentRoute: typeof LocaleAuthRouteRoute
    }
    '/$locale/auth/login/': {
      id: '/$locale/auth/login/'
      path: '/login'
      fullPath: '/$locale/auth/login'
      preLoaderRoute: typeof LocaleAuthLoginIndexRouteImport
      parentRoute: typeof LocaleAuthRouteRoute
    }
    '/$locale/auth/forgot-password/': {
      id: '/$locale/auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/$locale/auth/forgot-password'
      preLoaderRoute: typeof LocaleAuthForgotPasswordIndexRouteImport
      parentRoute: typeof LocaleAuthRouteRoute
    }
    '/$locale/(dashboard)/admin/': {
      id: '/$locale/(dashboard)/admin/'
      path: '/admin'
      fullPath: '/$locale/admin'
      preLoaderRoute: typeof LocaledashboardAdminIndexRouteImport
      parentRoute: typeof LocaledashboardRouteRoute
    }
  }
}

interface LocaledashboardRouteRouteChildren {
  LocaledashboardIndexRoute: typeof LocaledashboardIndexRoute
  LocaledashboardAdminIndexRoute: typeof LocaledashboardAdminIndexRoute
}

const LocaledashboardRouteRouteChildren: LocaledashboardRouteRouteChildren = {
  LocaledashboardIndexRoute: LocaledashboardIndexRoute,
  LocaledashboardAdminIndexRoute: LocaledashboardAdminIndexRoute,
}

const LocaledashboardRouteRouteWithChildren =
  LocaledashboardRouteRoute._addFileChildren(LocaledashboardRouteRouteChildren)

interface LocaleAuthRouteRouteChildren {
  LocaleAuthForgotPasswordIndexRoute: typeof LocaleAuthForgotPasswordIndexRoute
  LocaleAuthLoginIndexRoute: typeof LocaleAuthLoginIndexRoute
  LocaleAuthResendVerificationIndexRoute: typeof LocaleAuthResendVerificationIndexRoute
  LocaleAuthResetPasswordIndexRoute: typeof LocaleAuthResetPasswordIndexRoute
  LocaleAuthSignupIndexRoute: typeof LocaleAuthSignupIndexRoute
  LocaleAuthVerifyEmailIndexRoute: typeof LocaleAuthVerifyEmailIndexRoute
}

const LocaleAuthRouteRouteChildren: LocaleAuthRouteRouteChildren = {
  LocaleAuthForgotPasswordIndexRoute: LocaleAuthForgotPasswordIndexRoute,
  LocaleAuthLoginIndexRoute: LocaleAuthLoginIndexRoute,
  LocaleAuthResendVerificationIndexRoute:
    LocaleAuthResendVerificationIndexRoute,
  LocaleAuthResetPasswordIndexRoute: LocaleAuthResetPasswordIndexRoute,
  LocaleAuthSignupIndexRoute: LocaleAuthSignupIndexRoute,
  LocaleAuthVerifyEmailIndexRoute: LocaleAuthVerifyEmailIndexRoute,
}

const LocaleAuthRouteRouteWithChildren = LocaleAuthRouteRoute._addFileChildren(
  LocaleAuthRouteRouteChildren,
)

interface LocaleRouteRouteChildren {
  LocaledashboardRouteRoute: typeof LocaledashboardRouteRouteWithChildren
  LocaleAuthRouteRoute: typeof LocaleAuthRouteRouteWithChildren
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaledashboardRouteRoute: LocaledashboardRouteRouteWithChildren,
  LocaleAuthRouteRoute: LocaleAuthRouteRouteWithChildren,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
